### ISSUE TITLE
Doesn't work with new v4.3 .msx format

### ISSUE THREAD

**Issue by jduyon** [stefan-kolb/aoc-mgx-format#1]
I'm working on figuring out what changed between the MGX and MSX format (AOE2HD v4.3). Will you be working on this too?

**Comment by stefan-kolb** [comment]
I'm not actively working on this at the moment. What should definitely be different is the version header string. Apart from that I don' know any of the differences, however there should be some information on this in the web. There are some projects that support HD save games which may include the necessary information.
