### ISSUE TITLE
Unit actions

### ISSUE THREAD

**Issue by stefan-kolb** [stefan-kolb/aoc-mgx-format#2]
```
def Research
    int8 :command
    int24 :zero?
    int32 :object_id
    int16 :player_id
    int16 :technology_id
    int32 :constant?
end
```

Most actions (related to units?) always start with 4xint8 data, int32 object_id, ...

**Comment by coffenbacher** [comment]
So the int24 and int32 are unknown for Research? Am I understanding the issue correctly?

**Comment by stefan-kolb** [comment]
At least I don't know yet what they are for.
