### ISSUE TITLE
Hints in network protocol

### ISSUE THREAD

**Issue by heinezen** [stefan-kolb/aoc-mgx-format#4]
Hey, I'm doing a full analysis on the AoC network protocol [over here](https://github.com/SFTtech/openage/pull/877) and I might have some info for you.

1. `0x00` is also used for boarding a transport ship.
2. The value `0xff` for `selected_unit_count` is meant to be a reference to previously selected units. Whenever this turns up, it translates to "Do that action with the units from the previous command". This construct saves a lot of bandwith.
3. The action `0x67` is used for diplomacy (allied, neutral, enemy), but is also used for cheats and maybe other action like "resign". In the network protocol it looks like this

>`67` &mdash; command  
>`00` &mdash; context (different values for cheat, diplomacy, etc.)
>`01` &mdash; player_id_1 (who sends the offer)  
>`00` &mdash; zero
>`02` &mdash; player_id_2 (who receives the offer)
>`00 00 00 00 00` &mdash; zero
>`40 40 03` &mdash; relation  
>`00 00 00` &mdash; attacker id

The values for relation can be `00 00 00` (allied), `80 3f 01` (neutral) and `40 40 03` (enemies). When using cheats, the `player_id_2` field is used. Cheats start at value `0x65`.

EDIT:

4. Action `0x7e` is dropping a relic.
5. Action `0x1b` is Save & Exit.

**Comment by stefan-kolb** [comment]
Hi @heinezen 
You've done a great work inside the PR over inside Openage!
Why don't you consider contributing this back into this repository? 😄 
So we can create one repository for all these technological documentation, so a single point for this information.
I could also give you push rights and stuff!
I think it would be cool to gather all this information at one place and not always distribute it between different repositories.
Think about it!
Stefan

**Comment by heinezen** [comment]
Hey @stefan-kolb ,
I've already made plans to contribute all my finding back to you. After all, I took your format spec for my docs 😄. I wanted to finish the openage PR first which took longer than I expected, but I'll probably make the final changes over this weekend. When that is done, i'll make a PR here (and maybe check for some differences between networking and `.mgx` if there are any).

**Comment by stefan-kolb** [comment]
Sounds amazing 😄 👍
