### ISSUE TITLE
Could you please assign a LICENSE to the project?

### ISSUE THREAD

**Issue by jsjolen** [stefan-kolb/aoc-mgx-format#6]
Hi!

I'd like to do some parsing of your text files, could you please license this repo under MIT or WTFPL maybe?

**Comment by stefan-kolb** [comment]
Yeah sure, thanks for pointing this out 😄

**Comment by heinezen** [comment]
At least the contributions I PRed a while ago must be licensed under GPLv3, I think. They were taken straight from the openage repository.

**Comment by stefan-kolb** [comment]
Will fix that asap! Sorry for that.
